dist: bionic

services:
  - docker

before_install:
  - curl -L -o /tmp/podman.deb https://github.com/containers/libpod/releases/download/v3.0.1/podman_3.0.1-1_amd64.deb
  - sudo dpkg -i /tmp/podman.deb

script:
  - podman pull alpine
  - podman run alpine echo "Hello World"
  - podman images

after_script:
  - podman image prune -a -f
