dist: bionic

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  
jobs:
  include:
    - name: Podman Test
      script:
        - sudo docker exec ubuntu add-apt-repository ppa:projectatomic/ppa
        - sudo docker exec ubuntu apt update
        - sudo docker exec ubuntu apt install podman
        - sudo docker run -d --privileged --name ubuntu -v /sys/fs/cgroup:/sys/fs/cgroup:rw ubuntu:20.04 sleep infinity
        - sudo docker exec ubuntu apt-get update 
        - sudo docker exec ubuntu apt-get install -y podman
        - sudo docker exec ubuntu podman pull alpine 
        - sudo docker exec ubuntu podman run alpine echo Hello Podman!
  install: skip 

