dist: bionic
language: c 

env:
  - NATIVE_GOOS=linux NATIVE_GOARCH=amd64

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce make

jobs:
  include:
    - name: Podman tests
      script:
        - sudo docker run -d --privileged --name ubuntu ubuntu:22.04 sleep infinity
        - docker exec -e NATIVE_GOOS -e NATIVE_GOARCH ubuntu apt update
        - docker exec -e NATIVE_GOOS -e NATIVE_GOARCH ubuntu apt install -y git
        - sudo docker exec -e PATH=$PATH:/usr/local/sbin ubuntu bash -c "apt update && apt install -y git build-essential"
        - docker exec -e NATIVE_GOOS -e NATIVE_GOARCH ubuntu git clone https://github.com/containers/podman
        - docker exec -e NATIVE_GOOS -e NATIVE_GOARCH ubuntu apt install -y golang-go
        - docker exec -e NATIVE_GOOS -e NATIVE_GOARCH ubuntu make -C podman
        - docker exec -e NATIVE_GOOS -e NATIVE_GOARCH ubuntu make -C podman install
install: skip
